services:
  - type: web
    name: bellcorp-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false # You will be prompted for this value in the UI
      - key: JWT_SECRET
        generateValue: true # Render will generate a secure key for you
      - key: PORT
        value: 5000
